# Background of PCA
Say we are given a set $D = \{ ({\bf x}_{1}, y_1), ({\bf x}_{2}, y_2), \cdots, ({\bf x}_{N}, y_N) \} $, where each $y_i \in \{0, 1\}$ is the label for ${\bf x}_i \in \mathbb{R}^d$, a $d$ dimensional feature vector. We would like to know if we can reduce the dimensionality of features from 4 to 3, so we can envision it. We also want to find out how much "information" was lost in this dimensionality reduction.

As the first step we remove the mean from the data. To estimate the mean we use sample mean (unbiased ML estimation of the mean):

$$
{\hat {\bf x}}_{ML} = \frac{1}{N} \sum_{i=1}^N {\bf x}_i
$$

we define the mean-normalized row vector ${\bf b}_i$ as follows

$$
{\bf b}_i = ({\bf x}_i - {\hat {\bf x}}_{ML} )^T~~~,~i=1,...,N
$$

Using these we define the matrix ${ B}$ as follows

$$
B = \begin{bmatrix}
   -& {\bf b}_1 &-\\
   -&  {\bf b}_2 &-\\
    & \vdots & \\
   -&  {\bf b}_N &-
    \end{bmatrix}
$$
Here, each row is a mean-normalized feature vector (transposed).

We address two very similar ways to reduce dimensionality: with eigenvectors and with singular-value decomposition (SVD).

##Using SVD
You can find in most Linear Algebra texts the proof of SVD, that states that you can factor any real or complex $N \times d$ matrix into three factor-matrices:

$$
B= U \Sigma V^T   ~~~~~~~~~(1)
$$

where $U$ and $V$ are unitary matrices and $\Sigma$ is a diagonal matrix of singular values. $U$ is a square $N \times N$ matrix, $\Sigma$ is a diagonal, rectangular $N \times d$ matrix, and $V$ is a square $d \times d$ matrix.

**DEF: Unitary matrix** = an invertible, complex square matrix, $U$, is said to be "unitary" if its conjugate-transpose (also called its Hermitian transpose) is its also its inverse, so  $U^H\cdot U=(U^*)^T \cdot U=U\cdot U^H=I$. In our case, all our data is real-valued, so we need not bother with the commplex conjugate.

As we showed in the class, the principal components of the  data can be calculated by projecting the data into the matrix from equation $(1),~~~ V$

$$
T = B \cdot V
$$

Since we only work with real data and $V$ is a unitary matrix, then $VV^T = V^TV = I$.  

We interpret $V$ as the set of unit vectors along the axis of the new coordinate system. By projecting the data into these axis, you are changing the coordinate system from the original coordinate to the new coordinate where the features are independent among each other.  

The standard deviation of the data along each $i_{th}$ axis in this new cooordinate system is captured by the $\sigma_i$, where $\sigma_i$ is the $i_{th}$ diagonal element of the matrix $\Sigma$.

To reduce dimensionality, you select only the vectors of $V$ associated with the largest singular values in $\Sigma$, and project the data onto that subset of vectors.

##Using eigen-values and eigen-vectors
While SVD works for any shape rectangular matrix, such as our $N \times d$ matrix, $B$, eigen-values only work for square matrices.

*Observation:* If $B$ happened to be a square matrix already, then its eigenvalues would be the square of its singular values, $\lambda = \sigma^2$. However, for a general rectangular matrix, we cannot generalize this relationship.

To use PCA to reduce dimensionality from $d$ to $k$, we follow these steps:

1. First mean-normalize the data, as mentioned above, so we have the $N \times d$ matrix of mean-normalized feature vectors, $B$
2. Next, create a square, unbiased, ML estimate of the covariance matrix of feature vectors from $B$, so $C= B^T \cdot B $
3. Next, obtain the eigen-vector and eigen-value decomposition of $C$, where:
$$
C\cdot \vec{v}_i=\lambda_i \vec{v}_i~~,~~~~~i=1,...,d
$$
4. Next, select the $k$ largest eigen-values from the $d$ eigen-values obtained in step 3, and create a matrix with their associated eigen-vectors:
$$
V=\begin{bmatrix}
   |         &    & |\\
   \vec{v}_1 & \cdots & \vec{v}_k\\
   |         &    & |
    \end{bmatrix}
$$ (We happened to show indexes for the first $k$ eigen-vectors here because many functions in Matlab and Python return the decomposition with the eigen-values already sorted from largest to smallest. Make sure you select the largest ones.)
5. If the program has not already scaled the eigen-vectors to be unit-length, then do so now:
$$
\vec{u}_i = \frac{1}{||\vec{v}_i ||} \vec{v}_i ~~~~~~~ i=1, ... , k
$$
We are now ready to project our features onto the reduced dimensional feature space.
6. The matrix with reduced dimension feature vectors, $Z$ is
$$
Z= \begin{bmatrix}
   --  & \vec{u}_1^T  & --\\
    & \vdots  &  \\
   -- &  \vec{u}_k^T  & --
    \end{bmatrix}_{k \times d} \cdot
    \begin{bmatrix}
   |  &   & |\\
   \vec{x}^{(1)} & \cdots  & \vec{x}^{(N)} \\
   | &    & |
    \end{bmatrix}_{d \times N} \\
    =     \begin{bmatrix}
   |  &   & |\\
   \vec{z}^{(1)} & \cdots  & \vec{z}^{(N)} \\
   | &    & |
    \end{bmatrix}_{k \times N}
$$
7. Once we've trained my algorithm for classification or prediction, then any new instance that we wish to classify, or use for prediction must go through mean-normalization (step 1), and then projection onto the reduced-dimensional feature space (step 6).

##Reduction of Variance
The variance of our training set is our metric for information. Before PCA, the total variance from the original ($d$-dimensional) data is estimated to be:
$$
total~variance~original=\sum\limits_{j=1}^d \hat{\sigma}^2_{ML,j}
$$

The fraction-contribution of each feature is:
$$
proportion~from~feature~m=\frac{\hat{\sigma}^2_{ML,m}}{\sum\limits_{j=1}^d \hat{\sigma}^2_{ML,j}}~~~,~~m=1,...,d
$$
When you reduce the features' dimensions, you may want to limit the inforation you lost, so for example, you may want:
$$
\frac{total~variance~best~k~new~features}{total~variance~original} \ge 0.9
$$
This may place a constraint on how small $k$ is permitted to be.
***
***

**NOTE:** You are free to use SVD decomposition or eigenvevtor & eigenvalues to solve these problems. The choice is yours.

#Problem 1 [4 points]
Use the data that is generated in the next few lines to

*   Find the matrix $V$
*   Find the vectors that describe the new coordinate system in reduced diension $3$, and graph the data, so we can visualize it.

#Problem 2 [1 point]
*   Calculate how much the training set's variance has diminished. Have you preserved $90 \%$ of the variance?

***
***

The following code is provided to create 4-dimensional feature vectors collected in an $N \times 4$ matrix called "B":





In [1]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D  # Import 3D plotting module

# Enable interactive mode for Google Colab
%matplotlib notebook

# Install Plotly
!pip install plotly

# Import Plotly
import plotly.express as px

# Set a random seed for reproducibility
np.random.seed(42)

# Define the number of vectors you want to generate
num_vectors = 100

# Generate random values for the first dimension
dim1 = np.random.randn(num_vectors)

# Create the second dimension with dependency on the first dimension and random noise
dependency_factor_dim2 = 0.7
noise_dim2 = np.random.randn(num_vectors)
dim2 = dependency_factor_dim2 * dim1 + 2 + noise_dim2

# Create the third dimension with dependency on the second dimension and random noise
dependency_factor_dim3 = -1.1
noise_dim3 = np.random.randn(num_vectors)
dim3 = dependency_factor_dim3 * dim2 - 4 + noise_dim3

# Generate random values for the fourth dimension
dim4 = np.random.randn(num_vectors)

# Create a 4-dimensional vector by stacking the dimensions horizontally
B = np.column_stack((dim1, dim2, dim3, dim4))

# Create a 3D scatter plot of the first three dimensions using   (allows you to rotate the figure with your mouse)
fig = px.scatter_3d(x=dim1, y=dim2, z=dim3, color=dim4)
fig.update_layout(title='Interactive 3D Scatter Plot of Dimensions 1, 2, 3', scene=dict(xaxis_title='x_1', yaxis_title='x_2', zaxis_title='x_3'))

# Show the plot
fig.show()

In [2]:
# Calculate the covariance matrix C
C = np.cov(B, rowvar=False)
print("\nSample cov matrix:\n",C)

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(C)

# Sort eigenvectors by eigenvalues in descending order
sorted_indices = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[sorted_indices]
eigenvectors = eigenvectors[:, sorted_indices]

# Select the top 3 eigenvectors for the reduced dimension
k = 3
V = eigenvectors[:, :k]
print("\nEigenvectors:\n",V)
print("\nEigenvalues:\n",eigenvalues[:k])

# Project the data onto the reduced-dimensional space
mean_B = np.mean(B,axis=0)
normalisedB=B-mean_B
Z = normalisedB.dot(V)

# Create a 3D scatter plot of the reduced dimensions
fig = px.scatter_3d(x=Z[:, 0], y=Z[:, 1], z=Z[:, 2],color=dim4)
fig.update_layout(title='3D Scatter Plot of Reduced Dimensions', scene=dict(xaxis_title='z_1', yaxis_title='z_2', zaxis_title='z_3'))

# Show the plot
fig.show()

print(Z[:, 0])


Sample cov matrix:
 [[ 0.82476989  0.45918473 -0.31718095 -0.13667736]
 [ 0.45918473  1.14820587 -1.16935983 -0.11052422]
 [-0.31718095 -1.16935983  2.35893188  0.1213283 ]
 [-0.13667736 -0.11052422  0.1213283   0.78163531]]

Eigenvectors:
 [[ 0.21543116  0.69557149  0.48414346]
 [ 0.5217725   0.21156703  0.25244289]
 [-0.82179994  0.3710635   0.2108495 ]
 [-0.0773805  -0.57769505  0.81081452]]

Eigenvalues:
 [3.19594692 0.90874676 0.69716409]


[-1.48929652 -1.02920796 -0.49474908 -0.0531498   0.77550886  1.2093985
  4.23923165  0.9595129  -0.51227348 -2.44248479 -3.59453243 -1.4653657
 -0.3125737   0.74783703 -2.05349294 -0.72191488 -0.54036879 -0.91048191
  1.05713266 -0.54310267  1.1524385   0.0737451   1.7371374  -2.40833298
  0.79761877  2.61251394 -2.79557065  0.62873632  0.10858191 -1.52309316
 -2.18403322  2.39277132 -1.41846551  0.13543379 -1.99428449  0.37461681
  1.02067296 -2.80970461  0.21589121 -2.01712171  2.09112858  2.30285553
 -2.71034996 -0.61857289 -0.24493128  0.65393383 -1.66437606  0.20175686
 -0.07831921 -1.87643397  1.91835083 -0.68598281 -3.44550555  0.39308754
  3.07482452  0.7429123   0.75787412  1.06006316 -1.53042091  1.70309476
 -1.09373676  0.9830239   3.13728044 -1.65506746  2.66947013  3.44654994
 -0.11837124  5.2522294   0.59884931 -1.74928188 -1.86021229  2.00046676
 -1.06576783  2.45820064 -1.98865667  2.01213534  0.0488892   2.34442965
 -0.33698706  2.00146552  0.75298535 -1.13069942 -0.7

In [ ]:
# Calculate the total variance of the original data
total_variance_original = np.sum(np.var(B, axis=0))

new_variance = np.var(Z,axis=0)
total_new_variance=np.sum(new_variance)
total_new_variance
preserved = (total_new_variance/total_variance_original)*100

print(f"Total Variance of Original Data: {total_variance_original}")
print(f"Total Variance of Reduced Data: {total_new_variance}")
print(f"Variance preserved: {preserved:.2f}%" )

# Check if 90% of the variance is preserved
if total_new_variance/total_variance_original >= 0.9:
    print("90% of the Variance is Preserved.")
else:
    print("90% of the Variance is Not Preserved.")

Total Variance of Original Data: 5.062407538235173
Total Variance of Reduced Data: 4.753839190050944
Variance preserved: 93.90%
90% of the Variance is Preserved.
